name: test_stor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_sign_in: any
  google_fonts: any
  internet_connection_checker: any

  syncfusion_flutter_pdf: any
  printing: any

  provider: any
  flutter_bloc: any
  equatable: any

  dio: any

  shared_preferences: any
  intl: any
  image_picker: any
  cached_network_image: any
  url_launcher: any
  share_plus: any
  flutter_riverpod: any

  go_router: any
  flutter_local_notifications: any
  workmanager: any
  translator: any

  hive: any
  hive_flutter: any

  fluttertoast: any
  awesome_dialog: any
  fl_chart: ^0.64.0
  file_picker: any
  http: any
  flutter_html: any
  lottie: any

  connectivity_plus: any
  shimmer: any
  permission_handler: any
  animated_toggle_switch: any
  flutter_rating_bar: any
  timezone: any
  visibility_detector: any
